name: Coverage badge

on:
  push:
    branches: [ "debt/increase-test-coverage" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3.0.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}